### ISSUE TITLE
gal_eigenspec_Yip2004.fits not found

### ISSUE THREAD

**Issue by jcjiang-dev** [rudolffu/qsofitmore#9]
Hello developer, I have the following codes, the last part of which is to fit my optical spectrum as the following.

q = QSOFitNew(lam=lam_vals, flux=flux_vals, err=err_vals,z=z_vals, ra=ra_vals, dec=dec_vals,name='sdssj1507', is_sdss=False, path=path)
q.setmapname("sfd")
q.Fit(name = "Test1", deredden = True, wave_range = None, wave_mask =None, decomposition_host = True, Mi = None, npca_gal = 5, npca_qso = 20, Fe_uv_op = True, poly = True, BC = False, MC = True, n_trails = 20, linefit = True, tie_lambda = True, tie_width = True, tie_flux_1 = True, tie_flux_2 = True, save_result = True, plot_fig = True, save_fig = True, plot_line_name = True, plot_legend = False, save_fig_path = "output/", save_fits_path = "output/", save_fits_name = "Test1.fits")

I have received the following error. 

Traceback (most recent call last):
  File "optical_fitting.py", line 95, in <module>
    q.Fit(name = "Test1", deredden = True, wave_range = None, wave_mask =None, decomposition_host = True, Mi = None, npca_gal = 5, npca_qso = 20, Fe_uv_op = True, poly = True, BC = False, MC = True, n_trails = 20, linefit = True, tie_lambda = True, tie_width = True, tie_flux_1 = True, tie_flux_2 = True, save_result = True, plot_fig = True, save_fig = True, plot_line_name = True, plot_legend = False, save_fig_path = "output/", save_fits_path = "output/", save_fits_name = "Test1.fits")
  File "/home/jiachen/.local/lib/python3.8/site-packages/qsofitmore/fitmodule.py", line 902, in Fit
    self._DoDecomposition(self.wave, self.flux, self.err, self.path)
  File "/home/jiachen/.local/lib/python3.8/site-packages/qsofitmore/fitmodule.py", line 1963, in _DoDecomposition
    datacube = self._HostDecompose(self.wave, self.flux, self.err, self.z, self.Mi, self.npca_gal, self.npca_qso,
  File "/home/jiachen/.local/lib/python3.8/site-packages/qsofitmore/fitmodule.py", line 2024, in _HostDecompose
    galaxy = fits.open(path+'pca/Yip_pca_templates/gal_eigenspec_Yip2004.fits')
  File "/home/jiachen/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 214, in fitsopen
    return HDUList.fromfile(
  File "/home/jiachen/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 482, in fromfile
    return cls._readfrom(
  File "/home/jiachen/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1170, in _readfrom
    fileobj = _File(
  File "/home/jiachen/.local/lib/python3.8/site-packages/astropy/io/fits/file.py", line 218, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/jiachen/.local/lib/python3.8/site-packages/astropy/io/fits/file.py", line 636, in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])
FileNotFoundError: [Errno 2] No such file or directory: '/home/jiachen/.local/lib/python3.8/site-packages/qsofitmore/data/pca/Yip_pca_templates/gal_eigenspec_Yip2004.fits'

When calling Qsofitmore, it can't locate the file gal_eigenspec_Yip2004.fits. When I checked the directory, the /qsofitmore directory doesn't ./data subdirectory, as shown below.

ls /home/jiachen/.local/lib/python3.8/site-packages/qsofitmore/
__init__.py  __pycache__  auxmodule.py  config.py  extinction.py  fitmodule.py

May I ask whether I have missed anything when installing Qsofitmore?

Thank you very much.

**Comment by rudolffu** [comment]
Hi, I have included the package data in the new setup.py file. Please download the new package and see if the issue is solved.

**Comment by jcjiang-dev** [comment]
It weirdly produced a qsofitmore directory under the qsofitmore parent directory. I just manually moved the data directory one level up and it worked. Thank you.
